### ISSUE TITLE
Backport to 1.3.1

### ISSUE THREAD

**Issue by 7ranceaddic7** [linuxgurugamer/PartInfo#1]
LGG,

If there isn't too much trouble in doing so, would it be possible to get a backport to 1.3.1? If it requires more than just recompiling, nevermind.

Because UbioZurWelding does not work in the current versions (1.6+), I attempted to recompile this for 1.3.1 in MonoDevelop but got this ...

===== Begin ===
Building solution PartInfo (Debug)
Build started 5/8/2019 12:37:24 PM.
__________________________________________________
Project "/home/scott/GitHub/PartInfo/PartInfo/PartInfo.csproj" (Build target(s)):

Target PreBuildEvent:
    
    
    set textTemplatingPath="%ProgramFiles(x86)%/Microsoft Visual Studio/2017/Community/Common7/IDE/texttransform.exe"
    
    
    
    %textTemplatingPath% "/home/scott/GitHub/PartInfo/PartInfo/AssemblyVersion.tt
    /usr/bin/sh: 9: /tmp/tmpa6b5c5054f714982aed4e41742d69103.exec.cmd: Syntax error: Unterminated quoted string
    /usr/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(1348,5): error MSB3073: The command "
    /usr/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(1348,5): error MSB3073: 
    /usr/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(1348,5): error MSB3073: set textTemplatingPath="%ProgramFiles(x86)%/Microsoft Visual Studio/2017/Community/Common7/IDE/texttransform.exe"
    /usr/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(1348,5): error MSB3073: 
    /usr/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(1348,5): error MSB3073: 
    /usr/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(1348,5): error MSB3073: 
    /usr/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(1348,5): error MSB3073: %textTemplatingPath% "/home/scott/GitHub/PartInfo/PartInfo/AssemblyVersion.tt" exited with code 2.
Done building target "PreBuildEvent" in project "PartInfo.csproj" -- FAILED.

Done building project "PartInfo.csproj" -- FAILED.

Build FAILED.

/usr/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(1348,5): error MSB3073: The command "
/usr/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(1348,5): error MSB3073: 
/usr/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(1348,5): error MSB3073: set textTemplatingPath="%ProgramFiles(x86)%/Microsoft Visual Studio/2017/Community/Common7/IDE/texttransform.exe"
/usr/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(1348,5): error MSB3073: 
/usr/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(1348,5): error MSB3073: 
/usr/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(1348,5): error MSB3073: 
/usr/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(1348,5): error MSB3073: %textTemplatingPath% "/home/scott/GitHub/PartInfo/PartInfo/AssemblyVersion.tt" exited with code 2.
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.19

========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Build: 1 error, 0 warnings

===== End =====

**Comment by 7ranceaddic7** [comment]
Seems to be a common thing with all your mods, I'm starting to think you use MSVS for development. ;)

What would be even better is if you could direct me on how to correct MonoDevelop that I might do all this for myself in the future.

**Comment by 7ranceaddic7** [comment]
More digging and I found this in the .csproj

<PropertyGroup>
    <PreBuildEvent>set textTemplatingPath="%25ProgramFiles(x86)%25\Microsoft Visual Studio\2017\Community\Common7\IDE\texttransform.exe"

%25textTemplatingPath%25 "$(ProjectDir)AssemblyVersion.tt"</PreBuildEvent>
</PropertyGroup>

Yet, when I change it to this ...
<PropertyGroup>
    <PreBuildEvent>set textTemplatingPath="/usr/lib/monodevelop/AddIns/MonoDevelop.TextTemplating/TextTransform.exe"

%25textTemplatingPath%25 "$(ProjectDir)AssemblyVersion.tt"</PreBuildEvent>
</PropertyGroup>

I'm still generating the same error, just with the revised PATH.

**Comment by linuxgurugamer** [comment]
Just curious, have you tried the mod in 1.3.1 using the 1.4.5 version?

For you, just delete the prebuild and postbuild data, and move the dll by hand from the bin/debug or bin/release directory (depending on which way you are compiling it)

**Comment by linuxgurugamer** [comment]
Just an FYI, I just installed the 1.4.5 version in to a 1.3.1 game, works fine.

**Comment by 7ranceaddic7** [comment]
With 1.3 being 2+yo, no, that had not occur to me.

Yeah, it does work just fine.  As simple a plugin as it gets. (My reasoning failed me there.)

And, deleting those sections in .csproj is the solution.

P.S. You are a patient man; thanks for not biting my head off.
