### ISSUE TITLE
Feature request: show thrust curve of SRB in VAB

### ISSUE THREAD

**Issue by Gordon-Dry** [linuxgurugamer/PartInfo#5]
There are part packs with different thrust curves on each SRB, there is the Mod BetterSRBs etc.
But it's difficult to get the info about the actual thrust curve - the easiest way actually is to look into the ModuleManager.ConfigCache to be sure.

As the thrust curve is in ModuleEnginesFX and looks like this
```
			thrustCurve
			{
				key = 0    0.15  0    15
				key = 0.03 0.86  0.5  0.5
				key = 1    1    -0.37    0
			}

```
it should be possible.

Sometimes a thrust curve has more than 3 keys. Sometimes it has just 2.
Sometimes a prefab is referenced, like for example
`		ThrustCurvePrefab = steadydrop_66`
which seems to be stock and also should be derived somehow.

As some mods - like Bluedog_DB - check for prefabs, delete them and provide own thrustCurves, this check has to be done after all patching is done.

First I considered trying to make MM patches, but checking how many key entries a thrustCurve got or even trying to fiddle with prefabs made me decide not to try it. And those stock prefabs are not sitting in *.cfg files neither, so code is needed to derive them.

**Comment by linuxgurugamer** [comment]
A bit late, but I'm looking into this a bit

**Comment by linuxgurugamer** [comment]
I have this working for stock ModuleEngine and ModuleEngineFX, but found that the B9PartSwitch module has it's own curves which the normal query on the ModuleEngine doesn't return.   So not yet ready to release it
