### ISSUE TITLE
Implementing OnGUI() on a PartModule present on all parts has an unacceptable performance overhead

### ISSUE THREAD

**Issue by gotmachine** [linuxgurugamer/PartInfo#6]
`OnGUI()` methods have a heavy structural overhead, even if they aren't showing anything. Having it implemented on a `PartModule` in general, but moreover on one that is spammed on every part is a notable cause of linear with part count performance degradation.

Profiling with a 450 parts vessel in flight, about 15% of the frame time (~2.5 ms on my machine) is imputable to `ModulePartInfo.OnGUI()`, as well as about 160 Kb/frame of GC allocations, wasted doing basically nothing.

Could you consider either moving that GUI to a single `KSPAddon`, or maybe reimplementing it using the UGUI based `DialogGUI` API ?

**Comment by linuxgurugamer** [comment]
I'll look into moving it into a new MonoBehaviour which will only get instantiated with AddComponent when needed, that should solve the problem.

I don't know UGUI at this time

**Comment by linuxgurugamer** [comment]
Unless you have any other comments, can you close this so I know your comments are done?
Thanks

I've gotten the changes done, am testing now, hope to release it on Sunday
